# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_courseorg_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, verbose_name='\u8bb2\u5e08\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(default='', max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9'),
        ),
    ]
