# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_courseorg_course_nums'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Teacher', verbose_name='\u8bfe\u7a0b\u6559\u5e08'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_need_konow',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.CharField(default='', max_length=20, verbose_name='\u5b66\u4e60\u65f6\u957f'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='', verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
