# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_courseorg_course_nums'),
        ('courses', '0002_auto_20170123_1644'),
    ]

    operations = [

        migrations.AddField(
            model_name='course',
            name='course_you_learn',
            field=models.CharField(default='', max_length=200, verbose_name='\u5b66\u5230\u77e5\u8bc6'),
        ),

    ]
